### ISSUE TITLE
DeviceEventAdapter not triggering iAmReceived

### ISSUE THREAD

**Issue by WhittlesJr** [Frozenlock/bacure#30]
I've tried multiple versions of bacure and I'm failing to get this to work recently, so it's probably an issue with my environment or config or something. 

`bacure.core/boot-up!` and  `bacure.remote-device/discover-network` aren't adding remote devices for me anymore. I see the IAm responses coming in Wireshark, but I tried dropping some debug `prn` statements in `iAmReceived` but they never trigger. I just end up with an empty set of remote devices. Anything coming to mind that I might be doing wrong?

```
> ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether f8:b1:56:d7:a4:e9 brd ff:ff:ff:ff:ff:ff
    inet 10.200.84.88/24 scope global eno1
       valid_lft forever preferred_lft forever
    inet6 fe80::fab1:56ff:fed7:a4e9/64 scope link 
       valid_lft forever preferred_lft forever
```

```
(bacure.core/boot-up! {:broadcast-address "10.200.84.255"})
```

[bacure-capture.zip](https://github.com/Frozenlock/bacure/files/4036247/bacure-capture.zip)

**Comment by Frozenlock** [comment]
You can try to run [Wacnet](https://hvac.io/wacnet/wacnet-2.1.6-standalone.jar), it's built using Bacure.

If it finds the devices on your network you'll know you have something wrong in your current bacure configuration.

If it can't find the devices you probably have a problem with the network itself. (For example it's not on the same subnet or it has a different port.)

**Comment by WhittlesJr** [comment]
I'm guessing `java -jar` won't work on my distro (NixOS):

```
> java -jar ../../../Downloads/wacnet-2.1.6-standalone.jar --help
Exception in thread "BACnet4J IP socket listener for device 1338" java.lang.IllegalArgumentException: IP address must have 4 parts, not 16
        at com.serotonin.bacnet4j.npdu.ip.IpNetworkUtils.toBytes(IpNetworkUtils.java:78)
        at com.serotonin.bacnet4j.npdu.ip.IpNetworkUtils.toOctetString(IpNetworkUtils.java:59)
        at com.serotonin.bacnet4j.npdu.ip.IpNetwork.run(IpNetwork.java:334)
        at java.lang.Thread.run(Thread.java:748)



---> 
     See the web interface at http://localhost:47800.
     You can also connect to the Clojure nrepl on port 47999.
Exception in thread "main" java.lang.ExceptionInInitializerError
        at dorkbox.util.jna.linux.GtkEventDispatch.startGui(GtkEventDispatch.java:79)
        at dorkbox.systemTray.SystemTray.init(SystemTray.java:957)
        at dorkbox.systemTray.SystemTray.get(SystemTray.java:1167)
        at wacnet.systray$initialize_systray_BANG_.invokeStatic(systray.clj:27)
        at wacnet.systray$initialize_systray_BANG_.invoke(systray.clj:27)
        at wacnet.server$_main.invokeStatic(server.clj:38)
        at wacnet.server$_main.doInvoke(server.clj:26)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at wacnet.server.main(Unknown Source)
Caused by: java.lang.RuntimeException: We apologize for this, but we are unable to determine the GTK library is in use, or even if it is in use... Please create an issue for this and include your OS type and configuration.
        at dorkbox.util.jna.linux.GtkLoader.<clinit>(GtkLoader.java:241)
        ... 9 more
```


(Executables and libs don't reside in the standard locations on NixOS.) I could wrap it though...

**Comment by WhittlesJr** [comment]
Wouldn't ya know it, I had another instance of bacure running in another terminal somewhere on my system. Womp.
